import type { CardDefinitionId, CharacterCardDefinition } from "../engine/types";

const fixtureCharacters: CharacterCardDefinition[] = [
  {
    id: "character-302-18-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "18", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-302-18-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "내 차례 종료 직전, 마지막 행동을 끝낸 뒤, 차례마다 한 번, 손에 든 진주 카드를 모두 버린 후 획득 더미에서 버린 수 만큼 새 진주 카드를 획득할 수 있음",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-303-sum-10-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "합하면 '10'이 되는 카드들", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-303-sum-10-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "손 카드 제한이 1장 많아짐",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-304-12-p0-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "12", status: "candidate" },
    power: 0,
    diamondReward: 0,
    abilities: [
      {
        id: "character-304-12-p0-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "진주 8로 사용가능",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-305-6688-p3-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "6688", status: "candidate" },
    power: 3,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-306-11-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "11", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-306-11-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "진주 1로 사용가능",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-307-7777-p4-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "7777", status: "candidate" },
    power: 4,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-308-55-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "55", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-308-55-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "진주 5로 사용가능",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-400-12-p0-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "12", status: "candidate" },
    power: 0,
    diamondReward: 0,
    abilities: [
      {
        id: "character-400-12-p0-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "진주 8로 사용가능",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-401-357-p1-d1",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "357", status: "candidate" },
    power: 1,
    diamondReward: 1,
    abilities: [
      {
        id: "character-401-357-p1-d1-effect",
        timing: "unknown",
        status: "candidate",
        text: "다이아몬드를 사용해서 진주 카드의 값을 1 내릴 수 있음. 단, 진주 카드의 값을 '0'으로 만들 수는 없음. 진주 카드 1장에는 다이아몬드 하나만 사용가능. 사용한 다이아몬드는 버린 캐릭터 더미에 버림.",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-402-straight-3-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "연속되는 카드 3장", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-402-straight-3-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "내 차례 시작 직후, 첫 행동을 시작하기 전에, 캐릭터 획득 더미 맨 위 1장을 살펴볼 수 있음. 살펴본 카드는 제자리에 돌려놓음.",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-403-same-2-plus-66-p2-d1",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "같은 카드 2장 + 66", status: "candidate" },
    power: 2,
    diamondReward: 1,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-404-33-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "33", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-404-33-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "진주 3으로 사용가능",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-405-three-of-kind-p2-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "같은 카드 3장", status: "candidate" },
    power: 2,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-406-pair-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "같은 카드 2장", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-407-three-card-sum-20-p2-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "합하면 20이 되는 카드 3장", status: "candidate" },
    power: 2,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-408-odd-3-cards-p1-d1",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "홀수인 카드 3장", status: "candidate" },
    power: 1,
    diamondReward: 1,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-500-44-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "44", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-500-44-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "진주 4로 사용가능",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-501-88-p2-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "88", status: "candidate" },
    power: 2,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-502-sum-10-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "합하면 '10'이 되는 카드들", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-502-sum-10-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "손 카드 제한이 1장 많아짐",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-503-7777-p4-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "7777", status: "candidate" },
    power: 4,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-504-6688-p3-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "6688", status: "candidate" },
    power: 3,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-505-8888-p5-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "8888", status: "candidate" },
    power: 5,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-506-pair-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "같은 카드 2장", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-507-567-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "567", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-507-567-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "다른 플레이어 한 명의 손 카드를 보고, 그 중 1장을 가져옴",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-508-45678-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "45678", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-508-45678-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "이번 차례를 포함해서, 매 차례마다 행동 1회를 추가로 수행할 수 있음",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-600-222-1-plus-diamond-p3-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "222+다이아몬드 1장", status: "candidate" },
    power: 3,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-601-88-p2-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "88", status: "candidate" },
    power: 2,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-602-three-card-sum-7-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "합하면 7이 되는 카드 3장", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-602-three-card-sum-7-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "다른 플레이어 한 명의 관문에 있는 캐릭터 카드 중 1장을 버림",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-603-1111-p0-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "1111", status: "candidate" },
    power: 0,
    diamondReward: 0,
    abilities: [
      {
        id: "character-603-1111-p0-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "진주 '1~8'중 원하는 수로 사용가능",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-604-two-pairs-p2-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "같은 카드 2장씩 두 벌", status: "candidate" },
    power: 2,
    diamondReward: 0,
    abilities: [
      {
        id: "character-604-two-pairs-p2-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "다음 차례의 플레이어는 자신의 차례에 행동 1회를 추가로 수행",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-605-7788-p3-d1",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "7788", status: "candidate" },
    power: 3,
    diamondReward: 1,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-606-6688-p3-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "6688", status: "candidate" },
    power: 3,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-607-22-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "22", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-607-22-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "진주 2로 사용가능",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-608-333-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "333", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-608-333-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "캐릭터를 활성화할 때, 손에 든 '3' 진주 카드를 '1~8' 중 원하는 값으로 사용할 수 있음",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-700-straight-5-p2-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "연속되는 카드 5장", status: "candidate" },
    power: 2,
    diamondReward: 0,
    abilities: [
      {
        id: "character-700-straight-5-p2-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "내 차례 시작 직후, 첫 행동을 시작하기 전에, 내 관문에 있는 캐릭터 카드 1장을 열린 캐릭터 카드 1장과 서로 바꿀 수 있음",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-701-2468-p2-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "2468", status: "candidate" },
    power: 2,
    diamondReward: 0,
    abilities: [
      {
        id: "character-701-2468-p2-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "추가 행동 3회를 즉시 수행",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-702-1357-p2-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "1357", status: "candidate" },
    power: 2,
    diamondReward: 0,
    abilities: [
      {
        id: "character-702-1357-p2-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "추가 행동 3회를 즉시 수행",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-703-even-3-cards-p1-d1",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "짝수인 카드 3장", status: "candidate" },
    power: 1,
    diamondReward: 1,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-704-four-of-kind-p3-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "같은 카드 4장", status: "candidate" },
    power: 3,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-705-sum-10-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "합하면 '10'이 되는 카드들", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-705-sum-10-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "손 카드 제한이 1장 많아짐",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-706-three-of-kind-p2-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "같은 카드 3장", status: "candidate" },
    power: 2,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-707-333-or-666-p3-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "333/666", status: "candidate" },
    power: 3,
    diamondReward: 0,
    abilities: [
      {
        id: "character-707-333-or-666-p3-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "도깨비불은 관문에 거꾸로 놓는 유일한 캐릭터 카드임. 내 관문에 놓은 도깨비불을 내 양 옆 플레이어가 활성화시킬 수도 있음. 도깨비불을 활성화한 플레이어는 그 도깨비불을 가져가서 자신의 관문 오른쪽에 놓고 힘 3점을 얻음.",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-708-three-card-sum-10-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "합이 10이 되는 카드 3장", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-708-three-card-sum-10-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "캐릭터를 활성화할 때, 손에 든 '1' 진주 카드를 '8'인 것처럼 사용할 수 있음",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-800-345-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "345", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-800-345-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "방금 사용한 진주 카드 중 1장을 다시 가져옴",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-801-567-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "567", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-801-567-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "다른 플레이어 한 명의 손 카드를 보고, 그 중 1장을 가져옴",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-802-7788-p3-d1",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "7788", status: "candidate" },
    power: 3,
    diamondReward: 1,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-803-pair-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "같은 카드 2장", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-804-66-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "66", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-804-66-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "진주 6으로 사용가능",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-805-77-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "77", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-805-77-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "진주 7로 사용가능",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-806-2-p0-d1",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "2", status: "candidate" },
    power: 0,
    diamondReward: 1,
    abilities: [
      {
        id: "character-806-2-p0-d1-effect",
        timing: "unknown",
        status: "candidate",
        text: "손에 든 '2' 진주 카드 1장을 버리고 다이아몬드 1개를 가져올 수 있음",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-807-three-card-sum-7-p1-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "합하면 7이 되는 카드 3장", status: "candidate" },
    power: 1,
    diamondReward: 0,
    abilities: [
      {
        id: "character-807-three-card-sum-7-p1-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "다른 플레이어 한 명의 관문에 있는 캐릭터 카드 중 1장을 버림",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-808-1234-p1-d2",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "1234", status: "candidate" },
    power: 1,
    diamondReward: 2,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-900-same-2-plus-6x2-p2-d1",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "같은 카드 2장 + 6카드 2장", status: "candidate" },
    power: 2,
    diamondReward: 1,
    abilities: [],
    placement: "unknown",
    status: "candidate",
  },
  {
    id: "character-901-444-or-555-p3-d0",
    kind: "character",
    name: "인물 카드",
    requirement: { type: "custom", label: "444/555", status: "candidate" },
    power: 3,
    diamondReward: 0,
    abilities: [
      {
        id: "character-901-444-or-555-p3-d0-effect",
        timing: "unknown",
        status: "candidate",
        text: "도깨비불은 관문에 거꾸로 놓는 유일한 캐릭터 카드임. 내 관문에 놓은 도깨비불을 내 양 옆 플레이어가 활성화시킬 수도 있음. 도깨비불을 활성화한 플레이어는 그 도깨비불을 가져가서 자신의 관문 오른쪽에 놓고 힘 3점을 얻음.",
      },
    ],
    placement: "unknown",
    status: "candidate",
  },
];

export const fixtureCharacterDefinitions: Record<
  CardDefinitionId,
  CharacterCardDefinition
> = Object.fromEntries(fixtureCharacters.map((card) => [card.id, card]));

export function getFixtureCharacterDefinitionIds(): CardDefinitionId[] {
  return fixtureCharacters.map((card) => card.id);
}
